import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure and _category_.json files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
